#!/bin/bash

/usr/bin/feh --randomize --bg-fill /home/panthevm/Pictures/Wallpaper

/bin/cvt 1920 1080 60
/bin/xrandr --newmode "1920x1080_60.00"  173.00  1920 2048 2248 2576  1080 1083 1088 1120 -hsync +vsync
/bin/xrandr --addmode DP2 1920x1080_60.00
/bin/xrandr --output DP2 --mode 1920x1080_60.00

/usr/bin/picom --config /home/panthevm/.config/picom/picom.conf # --experimental-backends
