#! /bin/sh
bspc config border_width 2
bspc config window_gap   15

bspc config focused_border_color \#f47067
bspc config normal_border_color \#22272e

bspc config split_ratio          0.50
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc config focus_follows_pointer   true
bspc config pointer_follows_focus   true
bspc config pointer_follows_monitor true

# bspc monitor -d I II III IV V VI VII VIII IX X

bspc monitor eDP1 -d 1 2 3 4 5
bspc monitor DP2  -d 6 7 8 9 0

bspc rule -a Emacs state=tiled
